modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="colonyai"
version="${version}"
displayName="ColonyAI"
authors="sasha"
description='''
MineColonies assistant with modular GUI and Baritone integration.
'''

[[dependencies.colonyai]]
modId="forge"
mandatory=true
versionRange="[36.2.34,)"
ordering="NONE"
side="CLIENT"
